insert into message (content, user_id_send, user_id_recived) values ('Displ seg fx shaft of r tibia, init for opn fx type 3A/B/C', 2, 16);
insert into message (content, user_id_send, user_id_recived) values ('Subluxation of T1/T2 thoracic vertebra, subsequent encounter', 11, 16);
insert into message (content, user_id_send, user_id_recived) values ('Open wound of unspecified buttock', 8, 2);
insert into message (content, user_id_send, user_id_recived) values ('Fracture of anterior process of calcaneus', 2, 3);
insert into message (content, user_id_send, user_id_recived) values ('Hang-glider collision injuring occupant, initial encounter', 12, 5);
insert into message (content, user_id_send, user_id_recived) values ('Complications of genitourinary prosth dev/grft', 9, 7);
insert into message (content, user_id_send, user_id_recived) values ('Nondisplaced fracture of fourth metatarsal bone, left foot', 15, 17);
insert into message (content, user_id_send, user_id_recived) values ('Subluxation of L3/L4 lumbar vertebra, sequela', 14, 8);
insert into message (content, user_id_send, user_id_recived) values ('Unsp fx shaft of l rad, subs for opn fx type I/2 w nonunion', 23, 15);
insert into message (content, user_id_send, user_id_recived) values ('Unspecified aircraft accident injuring occupant, subs encntr', 7, 18);
insert into message (content, user_id_send, user_id_recived) values ('Scombroid fish poisoning, accidental (unintentional)', 25, 19);
insert into message (content, user_id_send, user_id_recived) values ('Nondisp midcervical fx l femr, subs for clos fx w delay heal', 19, 2);
insert into message (content, user_id_send, user_id_recived) values ('Maternal care for chromosomal abnormality in fetus, fetus 3', 14, 19);
insert into message (content, user_id_send, user_id_recived) values ('Sltr-haris Type III physl fx lower end ulna, right arm, init', 14, 3);
insert into message (content, user_id_send, user_id_recived) values ('Other chronic osteomyelitis, unspecified hand', 11, 24);
insert into message (content, user_id_send, user_id_recived) values ('Encounter for screening for other metabolic disorders', 12, 9);
insert into message (content, user_id_send, user_id_recived) values ('Car passenger injured in clsn w ped/anml nontraf, sequela', 4, 5);
insert into message (content, user_id_send, user_id_recived) values ('Burn of unsp degree of left hand, unsp site, init encntr', 11, 16);
insert into message (content, user_id_send, user_id_recived) values ('Breakdown of int fix of bones of foot and toes, sequela', 6, 5);
insert into message (content, user_id_send, user_id_recived) values ('Labor and delivery complicated by short cord, fetus 3', 12, 4);
insert into message (content, user_id_send, user_id_recived) values ('Fx unsp part of neck of left femur, init for opn fx type I/2', 20, 25);
insert into message (content, user_id_send, user_id_recived) values ('Unspecified acquired deformity of lower leg', 22, 24);
insert into message (content, user_id_send, user_id_recived) values ('Injury of external jugular vein', 4, 24);
insert into message (content, user_id_send, user_id_recived) values ('Colostomy hemorrhage', 22, 4);
insert into message (content, user_id_send, user_id_recived) values ('Unsp inj intrns musc/fasc/tend thmb at wrs/hnd lv, sequela', 14, 18);
insert into message (content, user_id_send, user_id_recived) values ('Mech compl of implanted penile prosthesis, initial encounter', 20, 6);
insert into message (content, user_id_send, user_id_recived) values ('Displaced fracture of anterior process of left calcaneus', 23, 19);
insert into message (content, user_id_send, user_id_recived) values ('Poisoning by unsp psychotropic drug, intentional self-harm', 10, 13);
insert into message (content, user_id_send, user_id_recived) values ('Hepatorenal syndrome', 1, 15);
insert into message (content, user_id_send, user_id_recived) values ('Disp fx of dist pole of navic bone of l wrs, 7thK', 21, 21);
